using System.Text.Json.Nodes;
using Skylab.Cms.Application.Contracts.Repositories;
using Skylab.Cms.Application.Contracts.Requests;
using Skylab.Cms.Application.Contracts.Services;
using Skylab.Cms.Application.Services;
using Skylab.Cms.Application.Services.Policies;
using Skylab.Cms.Domain.Entities;
using Skylab.Cms.Domain.Enums;
using Skylab.Cms.Domain.Exceptions;

namespace Skylab.Cms.Application.Tests;

public sealed class LifecycleContractTests
{
    [Fact]
    public async Task CollectionArchive_IsIdempotent_HiddenByDefault_AndVisibleOnlyToAuthorizedEditors()
    {
        var repository = new MemoryCollectionItemRepository();
        var item = CollectionItem.Create(
            CollectionKey.News,
            "reserved-story",
            NewsData("Reserved story"),
            "seed",
            DateTime.UtcNow.AddDays(-1));
        repository.Seed(item);
        var service = CreateCollectionService(repository);
        var privileged = PrincipalFactory.FromGroups("/UYELER/YK");
        var ordinaryMember = PrincipalFactory.FromGroups("/UYELER");

        var first = await service.ArchiveAsync(CollectionKey.News, item.Slug, privileged, "operator-1");
        var versionAfterFirstArchive = item.Version;
        var archivedAt = item.ArchivedAt;
        var second = await service.ArchiveAsync(CollectionKey.News, item.Slug, privileged, "operator-2");

        Assert.Null(await service.GetAsync(CollectionKey.News, item.Slug, privileged, "operator-1"));
        Assert.Empty(await service.ListArchivedAsync(CollectionKey.News, ordinaryMember));

        var archived = Assert.Single(await service.ListArchivedAsync(CollectionKey.News, privileged));
        Assert.Equal(item.Id, archived.Id);
        Assert.True(archived.IsArchived);
        Assert.Equal(archivedAt, archived.ArchivedAt);
        Assert.Equal("operator-1", archived.ArchivedBy);
        Assert.Equal(versionAfterFirstArchive, item.Version);
        Assert.Equal(first, second);
    }

    [Fact]
    public async Task CollectionRestore_IsIdempotent_AndReservedSlugCannotBeRecreated()
    {
        var repository = new MemoryCollectionItemRepository();
        var item = CollectionItem.Create(
            CollectionKey.News,
            "reserved-story",
            NewsData("Reserved story"),
            "seed",
            DateTime.UtcNow.AddDays(-1));
        item.Archive("original-archiver", DateTime.UtcNow.AddHours(-1));
        repository.Seed(item);
        var service = CreateCollectionService(repository);
        var privileged = PrincipalFactory.FromGroups("/UYELER/YK");

        var replacement = new UpsertCollectionItemRequest(NewsData("Replacement"), null);
        await Assert.ThrowsAsync<ConcurrencyConflictException>(() =>
            service.UpsertAsync(CollectionKey.News, item.Slug, replacement, privileged, "operator"));

        var first = await service.RestoreAsync(CollectionKey.News, item.Slug, privileged, "restorer-1");
        var versionAfterFirstRestore = item.Version;
        var second = await service.RestoreAsync(CollectionKey.News, item.Slug, privileged, "restorer-2");

        Assert.False(first.IsArchived);
        Assert.Null(first.ArchivedAt);
        Assert.Null(first.ArchivedBy);
        Assert.Equal(first, second);
        Assert.Equal(versionAfterFirstRestore, item.Version);
        Assert.NotNull(await service.GetAsync(CollectionKey.News, item.Slug, privileged, "restorer-1"));
        Assert.Single(repository.Items);
    }

    [Fact]
    public async Task CollectionRestore_RevalidatesUniqueSlugConflict()
    {
        var repository = new MemoryCollectionItemRepository();
        var archived = CollectionItem.Create(
            CollectionKey.News,
            "collision",
            NewsData("Archived"),
            "seed",
            DateTime.UtcNow.AddDays(-2));
        archived.Archive("archiver", DateTime.UtcNow.AddDays(-1));
        var conflictingActive = CollectionItem.Create(
            CollectionKey.News,
            "collision",
            NewsData("Active"),
            "seed",
            DateTime.UtcNow);
        repository.Seed(archived, conflictingActive);
        var service = CreateCollectionService(repository);
        var privileged = PrincipalFactory.FromGroups("/UYELER/YK");

        await Assert.ThrowsAsync<ConcurrencyConflictException>(() =>
            service.RestoreAsync(CollectionKey.News, archived.Slug, privileged, "restorer"));
        Assert.True(archived.IsArchived);
    }

    [Fact]
    public async Task AutoGeneratedCollectionSlug_SkipsArchivedReservation()
    {
        var repository = new MemoryCollectionItemRepository();
        var archived = CollectionItem.Create(
            CollectionKey.News,
            "reserved-story",
            NewsData("Reserved story"),
            "seed",
            DateTime.UtcNow.AddDays(-1));
        archived.Archive("archiver", DateTime.UtcNow);
        repository.Seed(archived);
        var service = CreateCollectionService(repository);

        var created = await service.CreateAutoSlugAsync(
            CollectionKey.News,
            new CreateCollectionItemRequest(NewsData("Reserved story")),
            PrincipalFactory.FromGroups("/UYELER/YK"),
            "operator");

        Assert.Equal("reserved-story-2", created.Slug);
        Assert.Equal(2, repository.Items.Count);
    }

    [Fact]
    public async Task CollectionArchive_RequiresCollectionEditAuthority()
    {
        var repository = new MemoryCollectionItemRepository();
        var item = CollectionItem.Create(
            CollectionKey.News,
            "club-news",
            NewsData("Club news"),
            "seed",
            DateTime.UtcNow);
        repository.Seed(item);
        var service = CreateCollectionService(repository);

        await Assert.ThrowsAsync<UnauthorizedAccessException>(() =>
            service.ArchiveAsync(CollectionKey.News, item.Slug, PrincipalFactory.FromGroups("/UYELER"), "member"));
        Assert.False(item.IsArchived);
    }

    [Fact]
    public async Task ContentSync_ArchivesAndRestoresIdempotently_PreservingLifecycleActorAndTime()
    {
        var repository = new MemoryContentBlockRepository();
        var draftService = new TrackingDraftService();
        var block = ContentBlock.Create(
            "skylab-site",
            "/home",
            "hero.title",
            BlockType.Text,
            JsonValue.Create("SKY LAB")!,
            0,
            "seed",
            DateTime.UtcNow.AddDays(-1));
        var otherClientBlock = ContentBlock.Create(
            "other-site",
            "/home",
            "hero.title",
            BlockType.Text,
            JsonValue.Create("Other")!,
            0,
            "seed",
            DateTime.UtcNow.AddDays(-1));
        otherClientBlock.Archive("other-operator", DateTime.UtcNow.AddHours(-4));
        repository.Seed(block, otherClientBlock);
        var service = new ContentService(repository, draftService);

        await service.SyncAsync("skylab-site", [], "deploy-1");
        var versionAfterFirstArchive = block.Version;
        var archivedAt = block.ArchivedAt;
        await service.SyncAsync("skylab-site", [], "deploy-2");

        Assert.Empty(await repository.GetBySlugAsync("skylab-site", "/home"));
        var archived = Assert.Single(await service.GetArchivedAsync("skylab-site"));
        Assert.Equal("hero.title", archived.BlockPath);
        Assert.Equal(archivedAt, archived.ArchivedAt);
        Assert.Equal("deploy-1", archived.ArchivedBy);
        Assert.Equal(versionAfterFirstArchive, block.Version);

        var manifest = new SyncManifestRequest(
            "/home",
            [new ManifestBlockItem("hero.title", BlockType.Text, JsonValue.Create("Default")!, 0)]);
        await service.SyncAsync("skylab-site", [manifest], "deploy-3");
        var versionAfterFirstRestore = block.Version;
        var repeated = await service.SyncAsync("skylab-site", [manifest], "deploy-4");

        Assert.False(block.IsArchived);
        Assert.Null(block.ArchivedAt);
        Assert.Null(block.ArchivedBy);
        Assert.Equal(versionAfterFirstRestore, block.Version);
        Assert.Equal(block.Id, Assert.Single(await repository.GetBySlugAsync("skylab-site", "/home")).Id);
        Assert.Equal(0, Assert.Single(repeated.Results).Restored);
        Assert.Equal(2, repository.Items.Count);
    }

    [Fact]
    public async Task PublishingContent_HardDeletesEphemeralRedisDraft()
    {
        var repository = new MemoryContentBlockRepository();
        var draftService = new TrackingDraftService();
        var block = ContentBlock.Create(
            "skylab-site",
            "/home",
            "hero.title",
            BlockType.Text,
            JsonValue.Create("Old")!,
            0,
            "seed",
            DateTime.UtcNow);
        repository.Seed(block);
        var service = new ContentService(repository, draftService);
        var request = new UpdatePageRequest(
            "/home",
            [new UpdateBlockItem("hero.title", JsonValue.Create("New")!, block.Version)]);

        await service.UpdatePageAsync("skylab-site", request, "editor");

        Assert.Equal(("skylab-site", "editor", "/home"), Assert.Single(draftService.Deleted));
    }

    private static CollectionService CreateCollectionService(MemoryCollectionItemRepository repository)
        => new(
            repository,
            new CollectionPolicyResolver([new NewsCollectionPolicy(), new TeamsCollectionPolicy()]),
            new NoopCollectionDraftService());

    private static JsonObject NewsData(string title) => new()
    {
        ["title"] = title,
        ["body"] = $"{title} body"
    };

    private sealed class MemoryCollectionItemRepository : ICollectionItemRepository
    {
        public List<CollectionItem> Items { get; } = [];

        public void Seed(params CollectionItem[] items) => Items.AddRange(items);

        public Task<IReadOnlyList<CollectionItem>> ListAsync(
            CollectionKey key,
            bool includeArchived = false,
            CancellationToken cancellationToken = default)
        {
            IEnumerable<CollectionItem> query = Items.Where(item => item.CollectionKey == key);
            if (!includeArchived)
                query = query.Where(item => !item.IsArchived);
            return Task.FromResult<IReadOnlyList<CollectionItem>>(query.OrderBy(item => item.Slug).ToList());
        }

        public Task<(IReadOnlyList<CollectionItem> Items, int Total)> ListPagedAsync(
            CollectionKey key,
            JsonObject? filterContainment,
            int offset,
            int limit,
            CancellationToken cancellationToken = default)
        {
            var matches = Items.Where(item => item.CollectionKey == key && !item.IsArchived).ToList();
            return Task.FromResult<(IReadOnlyList<CollectionItem>, int)>((matches.Skip(offset).Take(limit).ToList(), matches.Count));
        }

        public Task<CollectionItem?> GetBySlugAsync(
            CollectionKey key,
            string slug,
            bool includeArchived = false,
            CancellationToken cancellationToken = default)
        {
            var item = Items.FirstOrDefault(item =>
                item.CollectionKey == key
                && item.Slug == slug
                && (includeArchived || !item.IsArchived));
            return Task.FromResult(item);
        }

        public Task AddAsync(CollectionItem item, CancellationToken cancellationToken = default)
        {
            Items.Add(item);
            return Task.CompletedTask;
        }

        public Task<int> SaveChangesAsync(CancellationToken cancellationToken = default) => Task.FromResult(1);
    }

    private sealed class MemoryContentBlockRepository : IContentBlockRepository
    {
        public List<ContentBlock> Items { get; } = [];

        public void Seed(params ContentBlock[] items) => Items.AddRange(items);

        public Task<IReadOnlyList<ContentBlock>> GetBySlugAsync(
            string clientId,
            string slug,
            bool includeArchived = false,
            CancellationToken cancellationToken = default)
        {
            IEnumerable<ContentBlock> query = Items.Where(item => item.ClientId == clientId && item.Slug == slug);
            if (!includeArchived)
                query = query.Where(item => !item.IsArchived);
            return Task.FromResult<IReadOnlyList<ContentBlock>>(query.OrderBy(item => item.SortOrder).ToList());
        }

        public Task<IReadOnlyList<ContentBlock>> GetByClientAsync(
            string clientId,
            bool includeArchived = false,
            CancellationToken cancellationToken = default)
        {
            IEnumerable<ContentBlock> query = Items.Where(item => item.ClientId == clientId);
            if (!includeArchived)
                query = query.Where(item => !item.IsArchived);
            return Task.FromResult<IReadOnlyList<ContentBlock>>(query.ToList());
        }

        public Task AddRangeAsync(IEnumerable<ContentBlock> blocks, CancellationToken cancellationToken = default)
        {
            Items.AddRange(blocks);
            return Task.CompletedTask;
        }

        public Task<int> SaveChangesAsync(CancellationToken cancellationToken = default) => Task.FromResult(1);
    }

    private sealed class TrackingDraftService : IDraftService
    {
        public List<(string ClientId, string UserId, string Slug)> Deleted { get; } = [];

        public Task SaveDraftAsync(string clientId, string userId, string slug, IReadOnlyList<DraftBlock> blocks, CancellationToken cancellationToken = default)
            => Task.CompletedTask;

        public Task<IReadOnlyList<DraftBlock>?> GetDraftAsync(string clientId, string userId, string slug, CancellationToken cancellationToken = default)
            => Task.FromResult<IReadOnlyList<DraftBlock>?>(null);

        public Task DeleteDraftAsync(string clientId, string userId, string slug, CancellationToken cancellationToken = default)
        {
            Deleted.Add((clientId, userId, slug));
            return Task.CompletedTask;
        }
    }

    private sealed class NoopCollectionDraftService : ICollectionDraftService
    {
        public Task SaveItemDraftAsync(CollectionKey key, string slug, string userId, JsonObject data, CancellationToken cancellationToken = default) => Task.CompletedTask;
        public Task<CollectionDraft?> GetItemDraftAsync(CollectionKey key, string slug, string userId, CancellationToken cancellationToken = default) => Task.FromResult<CollectionDraft?>(null);
        public Task DeleteItemDraftAsync(CollectionKey key, string slug, string userId, CancellationToken cancellationToken = default) => Task.CompletedTask;
        public Task SaveVirtualDraftAsync(CollectionKey key, string slug, string userId, JsonObject data, CancellationToken cancellationToken = default) => Task.CompletedTask;
        public Task<CollectionDraft?> GetVirtualDraftAsync(CollectionKey key, string slug, string userId, CancellationToken cancellationToken = default) => Task.FromResult<CollectionDraft?>(null);
        public Task DeleteVirtualDraftAsync(CollectionKey key, string slug, string userId, CancellationToken cancellationToken = default) => Task.CompletedTask;
        public Task SaveNewDraftAsync(CollectionKey key, string userId, string? slug, JsonObject data, CancellationToken cancellationToken = default) => Task.CompletedTask;
        public Task<CollectionDraft?> GetNewDraftAsync(CollectionKey key, string userId, CancellationToken cancellationToken = default) => Task.FromResult<CollectionDraft?>(null);
        public Task DeleteNewDraftAsync(CollectionKey key, string userId, CancellationToken cancellationToken = default) => Task.CompletedTask;
    }
}
