using System.Security.Claims;
using System.Text.Json.Nodes;
using Skylab.Cms.Application.Contracts.Policies;
using Skylab.Cms.Application.Contracts.Schemas;
using Skylab.Cms.Application.Services.Helpers;
using Skylab.Cms.Domain.Enums;

namespace Skylab.Cms.Application.Services.Policies;

public sealed class NewsCollectionPolicy : ICollectionPolicy
{
    public CollectionKey Key => CollectionKey.News;

    public SlugSource SlugSource => SlugSource.AutoGenerated;

    public bool AllowAnonymousRead => true;

    public string? GetSlugSourceValue(JsonNode data) => data["title"]?.GetValue<string>();

    public CollectionSchema Schema { get; } = new([
        new("title", FieldType.Text, "Başlık", Required: true),
        new("summary", FieldType.Text, "Özet"),
        new("body", FieldType.RichText, "İçerik", Required: true),
        new("heroImage", FieldType.Url, "Kapak Görseli"),
        new("tags", FieldType.StringArray, "Etiketler", Filterable: true),
        new("author", FieldType.Text, "Yazar", Filterable: true),
        new("featured", FieldType.Bool, "Öne Çıkar", Filterable: true),
    ]);

    public bool CanEdit(ClaimsPrincipal user, string slug) => GroupPathParser.IsPrivileged(user);

    public bool CanCreate(ClaimsPrincipal user) => GroupPathParser.IsPrivileged(user);

    public Task<JsonNode> EnrichAsync(string slug, JsonNode data, CancellationToken cancellationToken = default)
        => Task.FromResult(data);
}
